<?php

declare(strict_types=1);

namespace App\Providers;

use App\Events;
use App\Events\Domains\DnsRecordVerified;
use App\Events\Domains\DomainCreated;
use App\Events\Domains\NameServerRecordVerified;
use App\Events\Pages\PageCreated;
use App\Events\Pages\PageUpdated;
use App\Listeners;
use App\Listeners\DebugEventListener;
use App\Listeners\Pages\GenerateNewRoutesFileFromDatabase;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event to listener mappings for the application.
     *
     * @var array<class-string, array<int, class-string>>
     */
    protected $listen = [
        NameServerRecordVerified::class => [
            DebugEventListener::class, // code: this is an autogenerated line
        ],
        DnsRecordVerified::class => [
        ],
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        PageCreated::class => [
            DebugEventListener::class, // code: this is an autogenerated line
            GenerateNewRoutesFileFromDatabase::class,
        ],
        PageUpdated::class => [
            DebugEventListener::class, // code: this is an autogenerated line
            GenerateNewRoutesFileFromDatabase::class,
        ],
        DomainCreated::class => [
            DebugEventListener::class, // code: this is an autogenerated line
            Listeners\Domains\UpdateDomainToUseCloudflareDns::class,
        ],
    ];

    /**
     * Register any events for your application.
     */
    public function boot(): void
    {
        //
    }

    /**
     * Determine if events and listeners should be automatically discovered.
     */
    public function shouldDiscoverEvents(): bool
    {
        return false;
    }
}
