name: Checks
on: [ pull_request ]
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!
      - name: setup php
        run: |
          ./bin/sail up -d
          git submodule init
          git submodule update --remote --merge
      - name: Install dependencies
        run: |
          sudo apt update
          ./bin/sail composer install
      - name: Run tests
        run: |
          cp .env.ci .env
          touch database/database.sqlite
          ./bin/sail art key:generate
          export $(cat .env | xargs)
          ./bin/sail test
      - name: tear down containers
        run: |
          ./bin/sail down
