name: PHP Unit
on: [ pull_request ]
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup php
        run: |
          git submodule init
          git submodule update --remote --merge
      - name: Install dependencies
        run: |
          touch storage/logs/laravel.log
          touch storage/logs/crontab.log
          touch storage/logs/horizon.log
          touch database/database.sqlite
          cp .env.ci .env
          ./bin/sail up -d
      - name: Run tests
        run: |
          ./bin/sail art key:generate
          export $(cat .env | xargs)
          ./bin/sail exec mariadb /docker-entrypoint-initdb.d/10-create-testing-database.sh
          ./bin/sail test
      - name: tear down containers
        run: |
          ./bin/sail down
