name: Checks
on: [ pull_request ]
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!
      - name: setup php
        run: |
          docker-compose up -d
          git submodule init
          git submodule update --remote --merge
      - name: Install dependencies
        run: |
          sudo apt update
          vendor/bin/sail composer install
      - name: Run tests
        run: |
          cp .env.ci .env
          touch database/database.sqlite
          vendor/bin/sail art key:generate
          export $(cat .env | xargs)
          vendor/bin/sail test
      - name: tear down containers
        run: |
          docker-compose down
