name: LaraStan Analysis
on: [ pull_request ]
jobs:
  larastan:
    name: Larastan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!
      - name: setup php
        run: |
          git submodule init
          git submodule update --remote --merge
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt remove mysql* -y
          touch storage/logs/laravel.log
          touch storage/logs/crontab.log
          touch storage/logs/horizon.log
          touch database/database.sqlite
          cp .env.ci .env
          ./bin/sail up -d
      - name: Larastan Analysis
        run: |
          ./bin/sail bin phpstan analyse --error-format=github

      - name: tear down containers
        run: |
          ./bin/sail down
